// CueMeIn Beta Form Handler API (Vercel Serverless Function)
export default async function handler(req, res) {
  // CORS headers setup (allow API calls from website)
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");

  // Handle OPTIONS request (browser preflight check)
  if (req.method === "OPTIONS") {
    return res.status(200).end();
  }

  // Only allow POST requests
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  try {
    // Get data from form submission
    const { email, name, message, honeypot } = req.body;

    // Spam prevention: honeypot field check
    if (honeypot) {
      return res.status(400).json({ error: "Spam detected" });
    }

    // Email format validation
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!email || !emailRegex.test(email)) {
      return res.status(400).json({ error: "Valid email is required" });
    }

    // Current time (Australian timezone)
    const timestamp = new Date().toLocaleString("en-AU", {
      timeZone: "Australia/Sydney",
      year: "numeric",
      month: "2-digit",
      day: "2-digit",
      hour: "2-digit",
      minute: "2-digit",
      second: "2-digit",
    });

    // Send email via Resend API
    const response = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${process.env.RESEND_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from: "CueMeIn Beta <noreply@cuemein.com.au>",
        to: ["beta@cuemein.com.au"],
        subject: "🎯 New CueMeIn Beta Signup!",
        html: `
          <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <div style="background: linear-gradient(135deg, #0EA5E9, #38BDF8); color: white; padding: 20px; border-radius: 10px 10px 0 0;">
              <h2>🎯 New Beta Application Received!</h2>
            </div>
            <div style="background: #f8f9fa; padding: 20px; border-radius: 0 0 10px 10px;">
              <div style="background: #e3f2fd; padding: 15px; border-left: 4px solid #2196f3; margin: 15px 0;">
                <p><strong>📧 Email:</strong> ${email}</p>
                <p><strong>👤 Name:</strong> ${name || "Not provided"}</p>
                <p><strong>💬 Message:</strong> ${message || "No message"}</p>
                <p><strong>⏰ Application Time:</strong> ${timestamp} (Sydney Time)</p>
              </div>

              <h3>📋 Next Steps:</h3>
              <ul>
                <li>✅ Add to beta tester list</li>
                <li>📧 Send welcome email</li>
                <li>📊 Update tracking spreadsheet</li>
              </ul>

              <div style="text-align: center; margin-top: 20px; color: #666; font-size: 12px;">
                <p>This email was automatically generated by CueMeIn Beta Application System</p>
              </div>
            </div>
          </div>
        `,
      }),
    });

    if (!response.ok) {
      throw new Error("Failed to send email");
    }

    // Success log (viewable in Vercel dashboard)
    console.log("✅ Beta application success:", {
      email,
      name: name || "Anonymous",
      timestamp,
      userAgent: req.headers["user-agent"]?.substring(0, 50),
    });

    // Success response
    return res.status(200).json({
      success: true,
      message: "Beta application completed! We'll be in touch soon. 🎉",
    });
  } catch (error) {
    // Error logging
    console.error("❌ Form submission error:", error);

    return res.status(500).json({
      error: "An error occurred. Please try again.",
      code: "INTERNAL_ERROR",
    });
  }
}
